spring.application.name=jpa

#Config bean of DataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/mor_mobile_baking
spring.datasource.username=postgres
spring.datasource.password=theara24



#Config Spring Data JPA
#1. DDL = Data Definition Language
#2. CREATE, ALTER, RENAME,...
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false
spring.threads.virtual.enabled=true